In [56]:
import math
import pandas as pd

In [62]:
pessoas = pd.read_csv('dados.csv', sep=';')
pessoas

  pessoa  valor
0      A    200
1      A    210
2      A    190
3      A    205
4      A    195
5      B     50
6      B    600
7      B     10
8      B    800
9      B    540

In [58]:
pessoas_resumo = pessoas.groupby('pessoa').count().rename(columns={'valor': 'contagem'}).reset_index().copy()
pessoas_media = pessoas.groupby('pessoa').mean().rename(columns={'valor': 'media'}).reset_index().copy()
pessoas = pessoas.merge(pessoas_media, how='left')
pessoas['diff_media_valor_quadrado'] = (pessoas.valor - pessoas.media) ** 2
soma_varianca = pessoas[['pessoa', 'diff_media_valor_quadrado']].groupby('pessoa').sum().reset_index().copy()

pessoas

  pessoa  valor  media  diff_media_valor_quadrado
0      A    200  200.0                        0.0
1      A    210  200.0                      100.0
2      A    190  200.0                      100.0
3      A    205  200.0                       25.0
4      A    195  200.0                       25.0
5      B     50  400.0                   122500.0
6      B    600  400.0                    40000.0
7      B     10  400.0                   152100.0
8      B    800  400.0                   160000.0
9      B    540  400.0                    19600.0

In [82]:
pessoas.groupby('pessoa').agg(['count', 'sum', 'mean', 'var', 'std'])

       valor
       count   sum   mean       var         std
pessoa
A          5  1000  200.0      62.5    7.905694
B          5  2000  400.0  123550.0  351.496799

In [92]:
pessoas_resumo = pessoas_resumo.merge(pessoas_media, how='left')
pessoas_resumo = pessoas_resumo.merge(soma_varianca, how='left')
pessoas_resumo['varianca'] = pessoas_resumo.diff_media_valor_quadrado / pessoas_resumo.contagem
pessoas_resumo['desvio_padrao'] = pessoas_resumo.varianca.apply(math.sqrt).round(2)
pessoas_resumo

  pessoa  contagem  media  diff_media_valor_quadrado  varianca  desvio_padrao
0      A         5  200.0                      250.0      50.0           7.07
1      B         5  400.0                   494200.0   98840.0         314.39

In [89]:
pessoas[pessoas.pessoa == 'B'].valor.std().round(2)

np.float64(351.5)

In [88]:
pessoas[pessoas.pessoa == 'B'].valor.std(ddof=0).round(2)

np.float64(314.39)